package com.infamous.infamous_legends.animation.keyframe_animations.definition;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class FirstOfOakKeyframeAnimations {

public static final AnimationDefinition FIRST_OF_OAK_SHOOT = AnimationDefinition.Builder.withLength(2.8343335f)
.addAnimation("everything",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 7f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 7f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("pelvis",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, -5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -5f, 7f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -5f, 7f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -5f, 7f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, -5f, -1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.6766665f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.7916765f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("pelvis",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.875f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.125f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.375f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.375f, KeyframeAnimations.posVec(0f, -3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.7083435f, KeyframeAnimations.posVec(0f, 1f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.8343335f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.625f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.25f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.7916765f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftArm",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -2f, 8f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -7.199999999999999f, 15.8f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -19f, 21f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.125f, KeyframeAnimations.posVec(0f, -19f, 21f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, -19f, 21.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, -19f, 21.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -18f, 12.600000000000001f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -18f, 12.600000000000001f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.2916765f, KeyframeAnimations.posVec(0f, -19f, 21.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.4583435f, KeyframeAnimations.posVec(0f, -9.44f, 15.87f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.6766665f, KeyframeAnimations.posVec(0f, 1.9900000000000002f, 3.67f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.7916765f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftArm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(-2.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(-2.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(2.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-67.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-90f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(-70f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-70f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(-70f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-63.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.625f, KeyframeAnimations.degreeVec(-63.09f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-53.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(-48.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-57.08f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.375f, KeyframeAnimations.degreeVec(-58.5f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightArm",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -2f, 8f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -7.199999999999999f, 15.8f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -19f, 21f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.125f, KeyframeAnimations.posVec(0f, -19f, 21f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, -19f, 21.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, -19f, 21.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -18f, 12.600000000000001f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -18f, 12.600000000000001f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.2916765f, KeyframeAnimations.posVec(0f, -19f, 21.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.4583435f, KeyframeAnimations.posVec(0f, -9.44f, 15.87f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.6766665f, KeyframeAnimations.posVec(0f, 1.9900000000000002f, 3.67f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.7916765f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightArm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(-2.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(-2.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(2.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-67.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-90f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(-70f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-70f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(-70f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-63.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.625f, KeyframeAnimations.degreeVec(-63.09f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-53.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(-48.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-57.08f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.375f, KeyframeAnimations.degreeVec(-58.5f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("nose",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, 6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5416767f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, 0f, 12f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 12f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 12f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0.5f, -4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0.5f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -1f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.625f, KeyframeAnimations.posVec(0f, -1f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -3f, 5f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -3f, 5f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -1f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.4583435f, KeyframeAnimations.posVec(0f, 1.68f, -0.27f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-29.976380948833594f, 1.2497024866634092f, 2.1654069746787172f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-34.976380948833594f, 1.2497024866634092f, 2.1654069746787172f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.625f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.25f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.2999999999999994f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.6999999999999998f, -3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -0.6999999999999998f, -3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -0.7f, -3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 4.3f, -3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -1.7000000000000002f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.625f, KeyframeAnimations.posVec(0f, -1.7000000000000002f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -2.7f, 8f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -2.7f, 8f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -1.7000000000000002f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.4583435f, KeyframeAnimations.posVec(0f, 2.58f, -0.44f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.625f, KeyframeAnimations.posVec(0f, -1.2999999999999994f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(7.609117593531664f, -2.497619044919702f, -0.0023786867823218927f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(15.11f, -2.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(15.11f, -2.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-4.890000000000001f, -2.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(15.012658796704144f, -4.635237611614684f, -2.8101894384017214f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.625f, KeyframeAnimations.degreeVec(15.012658796704144f, -4.635237611614684f, -2.8101894384017214f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-9.99f, -4.64f, -2.81f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(-9.99f, -4.64f, -2.81f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.25f, KeyframeAnimations.degreeVec(15.012658796704144f, -4.635237611614684f, -2.8101894384017214f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.625f, KeyframeAnimations.degreeVec(7.609117593531664f, -2.497619044919702f, -0.0023786867823218927f),
			AnimationChannel.Interpolations.CATMULLROM))).build();

public static final AnimationDefinition FIRST_OF_OAK_INACTIVE = AnimationDefinition.Builder.withLength(0.1f).looping()
.addAnimation("everything",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, -40f + 16, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-4.53f, -2.92f, -5.2f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftArm",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(24f, 2f, 23f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftArm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-11.06f, 31.46f, 17.39f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightArm",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(-14f, 21f, 10f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightArm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(11.66f, -16.21f, -0.9f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("nose",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(-23f, -5f, -25f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("nose",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(5.92f, -32.36f, 1.82f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(20f, 31f, -19f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-29.54f, 10.37f, -2.4f),
			AnimationChannel.Interpolations.LINEAR))).build();
public static final AnimationDefinition FIRST_OF_OAK_AWAKEN = AnimationDefinition.Builder.withLength(14.416766f)
.addAnimation("everything",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, -40f + 16, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(8.375f, KeyframeAnimations.posVec(0f, -40f + 16, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(8.416766f, KeyframeAnimations.posVec(0f, -40f + 16, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.583434f, KeyframeAnimations.posVec(0f, 26.07f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.208344f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.834334f, KeyframeAnimations.posVec(0f, 41f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(10.583434f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11.208344f, KeyframeAnimations.posVec(5f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11.676666f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.167666f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.375f, KeyframeAnimations.posVec(-5f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.834334f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.167666f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.416766f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.625f, KeyframeAnimations.posVec(0f, 45f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.958344f, KeyframeAnimations.posVec(0f, 43f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(14.167666f, KeyframeAnimations.posVec(0f, -1f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(14.25f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(14.343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(14.416766f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-4.53f, -2.92f, -5.2f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(8.416766f, KeyframeAnimations.degreeVec(-4.53f, -2.92f, -5.2f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(8.458344f, KeyframeAnimations.degreeVec(-4.53f, -2.92f, -5.2f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(8.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(9.416766f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(10.167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(10.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftArm",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(24f, 2f, 23f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.5834335f, KeyframeAnimations.posVec(24f, 2f, 23f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.625f, KeyframeAnimations.posVec(24f, 2f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.75f, KeyframeAnimations.posVec(29.96f, 32.25f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(3.2083435f, KeyframeAnimations.posVec(37f, 69f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(3.625f, KeyframeAnimations.posVec(37f, 67f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(4.125f, KeyframeAnimations.posVec(37f, 69f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(4.541677f, KeyframeAnimations.posVec(37f, 69f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.208344f, KeyframeAnimations.posVec(37f, 69f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.416766f, KeyframeAnimations.posVec(37f, 69f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.583434f, KeyframeAnimations.posVec(30f, 1f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.208344f, KeyframeAnimations.posVec(30f, -12f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.834334f, KeyframeAnimations.posVec(30f, -13f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(10.583434f, KeyframeAnimations.posVec(30f, -12f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11f, KeyframeAnimations.posVec(30.34f, -12.28f, 23.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11.208344f, KeyframeAnimations.posVec(25.5f, -12.45f, 23.88f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11.676666f, KeyframeAnimations.posVec(30.34f, -12.28f, 23.6f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12f, KeyframeAnimations.posVec(30f, -12f, 23f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.083434f, KeyframeAnimations.posVec(18.72f, -0.49f, 3.35f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.208344f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftArm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-11.06f, 31.46f, 17.39f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2.625f, KeyframeAnimations.degreeVec(-11.06f, 31.46f, 17.39f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-11.06f, 31.46f, 17.39f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.7916765f, KeyframeAnimations.degreeVec(-8.99f, 30.37f, 11.7f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3.125f, KeyframeAnimations.degreeVec(5f, 0f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3.75f, KeyframeAnimations.degreeVec(5f, -0.22f, 7.49f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(4.291677f, KeyframeAnimations.degreeVec(5f, 0f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(4.75f, KeyframeAnimations.degreeVec(5f, 0f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(8.416766f, KeyframeAnimations.degreeVec(5f, 0f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(8.583434f, KeyframeAnimations.degreeVec(5f, 0f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(9.208344f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(9.834334f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(10.583434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(11.958344f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(12.167666f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(12.291676f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(12.343334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.791676f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.958344f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.125f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.208344f, KeyframeAnimations.degreeVec(0f, 0f, -1f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightArm",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(-14f, 21f, 10f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.375f, KeyframeAnimations.posVec(-14f, 21f, 10f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.416767f, KeyframeAnimations.posVec(-14f, 21f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(5.583433f, KeyframeAnimations.posVec(-15.3f, 48.51f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(6f, KeyframeAnimations.posVec(-18f, 75f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(6.625f, KeyframeAnimations.posVec(-18f, 73f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(7.5f, KeyframeAnimations.posVec(-18f, 75f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.208344f, KeyframeAnimations.posVec(-18f, 75f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.416766f, KeyframeAnimations.posVec(-18f, 75f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.583434f, KeyframeAnimations.posVec(-21f, 7f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.208344f, KeyframeAnimations.posVec(-23f, -11f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.834334f, KeyframeAnimations.posVec(-23f, -12f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(10.583434f, KeyframeAnimations.posVec(-23f, -11f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(10.75f, KeyframeAnimations.posVec(-23f, -11f, 10f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(10.834334f, KeyframeAnimations.posVec(-16.19f, -0.74f, 7.04f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(10.958344f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11.041676f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightArm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(11.66f, -16.21f, -0.9f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(5.416767f, KeyframeAnimations.degreeVec(11.66f, -16.21f, -0.9f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(5.458343f, KeyframeAnimations.degreeVec(11.66f, -16.21f, -0.9f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(5.676667f, KeyframeAnimations.degreeVec(4.64f, 3.12f, 0.24f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.167667f, KeyframeAnimations.degreeVec(4.89f, 2.7f, 5.23f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.791677f, KeyframeAnimations.degreeVec(4.89f, 2.7f, 5.23f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(8.458344f, KeyframeAnimations.degreeVec(4.89f, 2.7f, 5.23f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(8.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(9.416766f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(10.167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(10.676666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(10.916766f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(11.041676f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(11.167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.791676f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.958344f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.125f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.208344f, KeyframeAnimations.degreeVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("nose",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(-23f, -5f, -25f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.125f, KeyframeAnimations.posVec(-23f, -5f, -25f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.20834334f, KeyframeAnimations.posVec(-23f, -5f, -25f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(-22f, 13.29f, -26f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.8343334f, KeyframeAnimations.posVec(-20f, 26f, -28f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.2916767f, KeyframeAnimations.posVec(-20f, 26f, -28f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.125f, KeyframeAnimations.posVec(-20f, 26f, -28f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.2083435f, KeyframeAnimations.posVec(-14.07f, 22.3f, -19.7f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.2916765f, KeyframeAnimations.posVec(-6.66f, 1.92f, -9.33f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("nose",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(5.92f, -32.36f, 1.82f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(7.19f, -29.59f, -0.74f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(1.83f, -30.09f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(3.28f, -29.98f, 2.11f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(3.28f, -29.98f, 2.11f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(-7.5f, 7.5f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(-7.5f, 7.5f, 5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.25f, KeyframeAnimations.degreeVec(-30.7f, 24.84f, 2.52f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(4.85f, 11.49f, 17.43f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(0f, 0f, 20f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 0f, 20f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.875f, KeyframeAnimations.degreeVec(0f, 0f, 20f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(13.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(13.916766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.041676f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.125f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.208344f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(20f, 31f, -19f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.125f, KeyframeAnimations.posVec(20f, 31f, -19f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.167667f, KeyframeAnimations.posVec(20f, 31f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(4.343333f, KeyframeAnimations.posVec(20f, 51.16f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(4.708343f, KeyframeAnimations.posVec(20f, 66f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(5.625f, KeyframeAnimations.posVec(20f, 65f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(6.5f, KeyframeAnimations.posVec(20f, 66f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.416766f, KeyframeAnimations.posVec(20f, 66f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(8.583434f, KeyframeAnimations.posVec(20f, -1f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.208344f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(9.834334f, KeyframeAnimations.posVec(20f, -14f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(10.583434f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11.208344f, KeyframeAnimations.posVec(15f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(11.676666f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.167666f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.375f, KeyframeAnimations.posVec(25f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(12.834334f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.167666f, KeyframeAnimations.posVec(20f, -15f, -19f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.291676f, KeyframeAnimations.posVec(6f, -13.5f, -18.5f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.375f, KeyframeAnimations.posVec(2.13f, -11.97f, -9.22f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.458344f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(13.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(14.041676f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(14.167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(14.208344f, KeyframeAnimations.posVec(0f, -1.3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-29.54f, 10.37f, -2.4f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(4.208343f, KeyframeAnimations.degreeVec(-29.54f, 10.37f, -2.4f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(4.25f, KeyframeAnimations.degreeVec(-29.54f, 10.37f, -2.4f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(4.458343f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(4.958343f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(5.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.291676f, KeyframeAnimations.degreeVec(-2.44f, -0.54f, -12.49f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.416766f, KeyframeAnimations.degreeVec(-19.94f, -0.54f, -12.49f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.541676f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.676666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(13.916766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.041676f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.167666f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(14.25f, KeyframeAnimations.degreeVec(7.61f, -2.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
}