package com.infamous.infamous_legends.animation.keyframe_animations.definition;

import com.infamous.infamous_legends.animation.sine_wave_animations.SineWaveAnimationUtils;
import com.infamous.infamous_legends.entities.RegalTiger;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class RegalTigerKeyframeAnimations {

private static float floatMax = Float.MAX_VALUE;

public static final AnimationDefinition REGAL_TIGER_SIT = AnimationDefinition.Builder.withLength(0.625f)
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, -0.25f, 1.1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tail",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tailTip",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 2.4999999999999996f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-15.013645338692186f, -2.4147632009153313f, 0.647430997556512f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(2f, -5.5f, 3f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-30f, 0f, -90f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 3f, 2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 3f, 2f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-11.25f, 1.08f, 1.4f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(7.4981f, 2.1524305189668667f, 2.804777560031198f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(-2f, -5.500000000000002f, 3f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-30f, 0f, 90f),
			AnimationChannel.Interpolations.CATMULLROM))).build();




public static AnimationDefinition REGAL_TIGER_CLEAN(RegalTiger entity) {
	return AnimationDefinition.Builder.withLength(7.5f).addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(-25 + SineWaveAnimationUtils.getSineWaveKeyframe(-0.5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.75f, KeyframeAnimations.degreeVec(-25 + SineWaveAnimationUtils.getSineWaveKeyframe(-0.5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3f, KeyframeAnimations.degreeVec(-25 + SineWaveAnimationUtils.getSineWaveKeyframe(-1F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7f, KeyframeAnimations.degreeVec(-25 + SineWaveAnimationUtils.getSineWaveKeyframe(-1F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7.5f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tail",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, SineWaveAnimationUtils.getSineWaveKeyframe(35F, 200, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.75f, KeyframeAnimations.degreeVec(0f, SineWaveAnimationUtils.getSineWaveKeyframe(35F, 200, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tailTip",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(30f, SineWaveAnimationUtils.getSineWaveKeyframe(35F, 200, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -75), 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.75f, KeyframeAnimations.degreeVec(30f, SineWaveAnimationUtils.getSineWaveKeyframe(35F, 200, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -75), 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7.5f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(46.3029F + SineWaveAnimationUtils.getSineWaveKeyframe(-2.5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -25), 10.547935953488377f, 14.043973275852295f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3f, KeyframeAnimations.degreeVec(46.3029F + SineWaveAnimationUtils.getSineWaveKeyframe(-2.5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -25), 10.55f, 14.04f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3.375f, KeyframeAnimations.degreeVec(58.0084F + SineWaveAnimationUtils.getSineWaveKeyframe(-5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -25), 2.5202F + SineWaveAnimationUtils.getSineWaveKeyframe(-7.5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -50), -21.6785377273172f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.875f, KeyframeAnimations.degreeVec(58.0084F + SineWaveAnimationUtils.getSineWaveKeyframe(-5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -25), 2.5202F + SineWaveAnimationUtils.getSineWaveKeyframe(-7.5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -50), -21.6785377273172f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7.25f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 2.4999999999999996f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 2.5F + SineWaveAnimationUtils.getSineWaveKeyframe(-0.1F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0)),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(6.5f, KeyframeAnimations.posVec(0f, 0f, 2.5F + SineWaveAnimationUtils.getSineWaveKeyframe(-0.1F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0)),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(7f, KeyframeAnimations.posVec(0f, 0f, 2.4999999999999996f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-15.013645338692186f, -2.4147632009153313f, 0.647430997556512f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-15.01F + SineWaveAnimationUtils.getSineWaveKeyframe(-0.75F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), -2.41f, 0.65f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.5f, KeyframeAnimations.degreeVec(-15.01F + SineWaveAnimationUtils.getSineWaveKeyframe(-0.75F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), -2.41f, 0.65f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7f, KeyframeAnimations.degreeVec(-15.013645338692186f, -2.4147632009153313f, 0.647430997556512f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(2f, -5.5f, 3f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-30f, 0f, -90f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, 2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 3f, 1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.875f, KeyframeAnimations.posVec(0f, 3f, 1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.125f, KeyframeAnimations.posVec(-1f, 7f, -1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(6.5f, KeyframeAnimations.posVec(-1f, 7f, -1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(7.125f, KeyframeAnimations.posVec(0f, 3f, 2f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(7.4981f, 2.1524305189668667f, 2.804777560031198f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(-70.0088F + SineWaveAnimationUtils.getSineWaveKeyframe(-5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -50), -0.29079959521241117f, 2.2590576414116184f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2.875f, KeyframeAnimations.degreeVec(-70.0088F + SineWaveAnimationUtils.getSineWaveKeyframe(-5F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -50), -0.29f, 2.26f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3.125f, KeyframeAnimations.degreeVec(-125.2673F + SineWaveAnimationUtils.getSineWaveKeyframe(-10F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -50), -6.310962551579942f, 6.741430672074111f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(6.5f, KeyframeAnimations.degreeVec(-125.2673F + SineWaveAnimationUtils.getSineWaveKeyframe(-10F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -50), -6.310962551579942f, 6.741430672074111f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7.125f, KeyframeAnimations.degreeVec(7.4981f, 2.1524305189668667f, 2.804777560031198f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(-2f, -5.500000000000002f, 3f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-30f, 0f, 90f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightEar",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(3.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(3.5f, KeyframeAnimations.degreeVec(9.3095F + SineWaveAnimationUtils.getSineWaveKeyframe(-10F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), -21.507171006051067f, 28.4669F + SineWaveAnimationUtils.getSineWaveKeyframe(-10F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, 50)),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7f, KeyframeAnimations.degreeVec(9.3095F + SineWaveAnimationUtils.getSineWaveKeyframe(-10F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, -0), -21.507171006051067f, 28.4669F + SineWaveAnimationUtils.getSineWaveKeyframe(-10F, 500, SineWaveAnimationUtils.getTick(entity.tickCount, true), -floatMax, floatMax, 50)),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(7.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
}


public static final AnimationDefinition REGAL_TIGER_STAND = AnimationDefinition.Builder.withLength(0.8343334f)
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 1f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, -0.75f, 0.11f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tail",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tailTip",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(27.02f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 2.4999999999999996f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-15.013645338692186f, -2.4147632009153313f, 0.647430997556512f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.08343333f, KeyframeAnimations.posVec(2f, -5.5f, 3f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-30f, 0f, -90f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, 2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 4f, 2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(7.4981f, 2.1524305189668667f, 2.804777560031198f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0.08343333f, KeyframeAnimations.posVec(-2f, -5.500000000000002f, 3f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-30f, 0f, 90f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
public static final AnimationDefinition REGAL_TIGER_ATTACK = AnimationDefinition.Builder.withLength(1.5f)
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 4f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 6f, -5f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 1f, -5f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, -1f, -1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tail",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("tailTip",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-4.924415151213452f, -0.8671724090795578f, -9.962710787263859f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(9.962710787264314f, 0.8671724090795578f, -4.924415151213907f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -1f, 2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(1.71f, 10.86f, -7.43f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.625f, KeyframeAnimations.posVec(3f, 11f, -11f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(2.5f, 2.5f, -13.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.8343334f, KeyframeAnimations.posVec(0.75f, -2.25f, -5.75f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.9167666f, KeyframeAnimations.posVec(0.25f, -0.75f, -6.92f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.125f, KeyframeAnimations.posVec(0.25f, -0.75f, -5.92f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, 2f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-105.24614699825815f, -5.295686736378578f, 5.318516490418922f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(-109.4088377878787f, 0.3512f, 4.183f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-62.53238317514328f, 7.8922f, 18.5581f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -0.5f, 4f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.5f, -2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -0.4999999999999998f, -3f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("leftBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -1f, 2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(-1.71f, 10.86f, -7.43f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.625f, KeyframeAnimations.posVec(-3f, 11f, -11f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(-2.5f, 2.5f, -13.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.8343334f, KeyframeAnimations.posVec(-0.75f, -2.25f, -5.75f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.9167666f, KeyframeAnimations.posVec(-0.25f, -0.75f, -6.92f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.125f, KeyframeAnimations.posVec(-0.25f, -0.75f, -5.92f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, 2f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightFrontLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-105.24614699825815f, 5.2957f, -5.3185f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(-109.4088377878787f, -0.3512f, -4.183f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-62.53238317514328f, -7.8922f, -18.5581f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -0.5f, 4f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.5f, -2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, -0.4999999999999998f, -3f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("rightBackLeg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
}